### ISSUE TITLE
ImportError: cannot import name 'AttentionLoss' from 'models.attentionnet'

### ISSUE THREAD

**Issue by pangshengwei** [1980x/ABAW2020DMACS#1]
There is no `AttentionLoss` function in attentionnet.py, how may we obtain it?

**Comment by 1980x** [comment]
Hi, thanks for your interest. AttentionLoss is not required as I have used only crossentropyloss for training. I missed correcting this in the uploaded code. Now, I have updated the file. Any queries, do let me know. Thanks
